// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen.js';
import { checkAuth, createEndpoint, createTarget, deleteEndpoint, deleteTarget, getEndpoint, healthz, ingress, listEndpoints, listEvents, listTargets, type Options, testSend, updateEndpoint } from '../sdk.gen.js';
import type { CheckAuthData, CreateEndpointData, CreateEndpointError, CreateEndpointResponse, CreateTargetData, CreateTargetError, CreateTargetResponse, DeleteEndpointData, DeleteEndpointError, DeleteEndpointResponse, DeleteTargetData, DeleteTargetError, DeleteTargetResponse, GetEndpointData, GetEndpointError, GetEndpointResponse, HealthzData, HealthzResponse, IngressData, IngressError, ListEndpointsData, ListEndpointsResponse, ListEventsData, ListEventsResponse, ListTargetsData, ListTargetsResponse, TestSendData, TestSendError, UpdateEndpointData, UpdateEndpointError, UpdateEndpointResponse } from '../types.gen.js';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const checkAuthQueryKey = (options?: Options<CheckAuthData>) => createQueryKey('checkAuth', options);

export const checkAuthOptions = (options?: Options<CheckAuthData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof checkAuthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await checkAuth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: checkAuthQueryKey(options)
});

export const listEndpointsQueryKey = (options?: Options<ListEndpointsData>) => createQueryKey('listEndpoints', options);

export const listEndpointsOptions = (options?: Options<ListEndpointsData>) => queryOptions<ListEndpointsResponse, DefaultError, ListEndpointsResponse, ReturnType<typeof listEndpointsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEndpoints({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEndpointsQueryKey(options)
});

export const createEndpointMutation = (options?: Partial<Options<CreateEndpointData>>): UseMutationOptions<CreateEndpointResponse, CreateEndpointError, Options<CreateEndpointData>> => {
    const mutationOptions: UseMutationOptions<CreateEndpointResponse, CreateEndpointError, Options<CreateEndpointData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createEndpoint({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteEndpointMutation = (options?: Partial<Options<DeleteEndpointData>>): UseMutationOptions<DeleteEndpointResponse, DeleteEndpointError, Options<DeleteEndpointData>> => {
    const mutationOptions: UseMutationOptions<DeleteEndpointResponse, DeleteEndpointError, Options<DeleteEndpointData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteEndpoint({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEndpointQueryKey = (options: Options<GetEndpointData>) => createQueryKey('getEndpoint', options);

export const getEndpointOptions = (options: Options<GetEndpointData>) => queryOptions<GetEndpointResponse, GetEndpointError, GetEndpointResponse, ReturnType<typeof getEndpointQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEndpoint({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEndpointQueryKey(options)
});

export const updateEndpointMutation = (options?: Partial<Options<UpdateEndpointData>>): UseMutationOptions<UpdateEndpointResponse, UpdateEndpointError, Options<UpdateEndpointData>> => {
    const mutationOptions: UseMutationOptions<UpdateEndpointResponse, UpdateEndpointError, Options<UpdateEndpointData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateEndpoint({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listTargetsQueryKey = (options: Options<ListTargetsData>) => createQueryKey('listTargets', options);

export const listTargetsOptions = (options: Options<ListTargetsData>) => queryOptions<ListTargetsResponse, DefaultError, ListTargetsResponse, ReturnType<typeof listTargetsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTargets({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTargetsQueryKey(options)
});

export const createTargetMutation = (options?: Partial<Options<CreateTargetData>>): UseMutationOptions<CreateTargetResponse, CreateTargetError, Options<CreateTargetData>> => {
    const mutationOptions: UseMutationOptions<CreateTargetResponse, CreateTargetError, Options<CreateTargetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTarget({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteTargetMutation = (options?: Partial<Options<DeleteTargetData>>): UseMutationOptions<DeleteTargetResponse, DeleteTargetError, Options<DeleteTargetData>> => {
    const mutationOptions: UseMutationOptions<DeleteTargetResponse, DeleteTargetError, Options<DeleteTargetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteTarget({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const testSendMutation = (options?: Partial<Options<TestSendData>>): UseMutationOptions<unknown, TestSendError, Options<TestSendData>> => {
    const mutationOptions: UseMutationOptions<unknown, TestSendError, Options<TestSendData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await testSend({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listEventsQueryKey = (options?: Options<ListEventsData>) => createQueryKey('listEvents', options);

export const listEventsOptions = (options?: Options<ListEventsData>) => queryOptions<ListEventsResponse, DefaultError, ListEventsResponse, ReturnType<typeof listEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEventsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listEventsInfiniteQueryKey = (options?: Options<ListEventsData>): QueryKey<Options<ListEventsData>> => createQueryKey('listEvents', options, true);

export const listEventsInfiniteOptions = (options?: Options<ListEventsData>) => infiniteQueryOptions<ListEventsResponse, DefaultError, InfiniteData<ListEventsResponse>, QueryKey<Options<ListEventsData>>, number | Pick<QueryKey<Options<ListEventsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListEventsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listEvents({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEventsInfiniteQueryKey(options)
});

export const healthzQueryKey = (options?: Options<HealthzData>) => createQueryKey('healthz', options);

export const healthzOptions = (options?: Options<HealthzData>) => queryOptions<HealthzResponse, DefaultError, HealthzResponse, ReturnType<typeof healthzQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthz({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthzQueryKey(options)
});

export const ingressMutation = (options?: Partial<Options<IngressData>>): UseMutationOptions<unknown, IngressError, Options<IngressData>> => {
    const mutationOptions: UseMutationOptions<unknown, IngressError, Options<IngressData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ingress({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
