// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen.js';
import { createEndpoint, createTarget, deleteTarget, healthz, ingress, listEndpoints, listEvents, listTargets, type Options, updateEndpoint } from '../sdk.gen.js';
import type { CreateEndpointData, CreateEndpointError, CreateEndpointResponse, CreateTargetData, CreateTargetError, CreateTargetResponse, DeleteTargetData, DeleteTargetError, DeleteTargetResponse, HealthzData, HealthzResponse, IngressData, IngressError, ListEndpointsData, ListEndpointsResponse, ListEventsData, ListEventsResponse, ListTargetsData, ListTargetsResponse, UpdateEndpointData, UpdateEndpointError, UpdateEndpointResponse } from '../types.gen.js';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listEndpointsQueryKey = (options?: Options<ListEndpointsData>) => createQueryKey('listEndpoints', options);

export const listEndpointsOptions = (options?: Options<ListEndpointsData>) => queryOptions<ListEndpointsResponse, DefaultError, ListEndpointsResponse, ReturnType<typeof listEndpointsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEndpoints({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEndpointsQueryKey(options)
});

export const createEndpointMutation = (options?: Partial<Options<CreateEndpointData>>): UseMutationOptions<CreateEndpointResponse, CreateEndpointError, Options<CreateEndpointData>> => {
    const mutationOptions: UseMutationOptions<CreateEndpointResponse, CreateEndpointError, Options<CreateEndpointData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createEndpoint({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateEndpointMutation = (options?: Partial<Options<UpdateEndpointData>>): UseMutationOptions<UpdateEndpointResponse, UpdateEndpointError, Options<UpdateEndpointData>> => {
    const mutationOptions: UseMutationOptions<UpdateEndpointResponse, UpdateEndpointError, Options<UpdateEndpointData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateEndpoint({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listEventsQueryKey = (options?: Options<ListEventsData>) => createQueryKey('listEvents', options);

export const listEventsOptions = (options?: Options<ListEventsData>) => queryOptions<ListEventsResponse, DefaultError, ListEventsResponse, ReturnType<typeof listEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEventsQueryKey(options)
});

export const listTargetsQueryKey = (options?: Options<ListTargetsData>) => createQueryKey('listTargets', options);

export const listTargetsOptions = (options?: Options<ListTargetsData>) => queryOptions<ListTargetsResponse, DefaultError, ListTargetsResponse, ReturnType<typeof listTargetsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTargets({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTargetsQueryKey(options)
});

export const createTargetMutation = (options?: Partial<Options<CreateTargetData>>): UseMutationOptions<CreateTargetResponse, CreateTargetError, Options<CreateTargetData>> => {
    const mutationOptions: UseMutationOptions<CreateTargetResponse, CreateTargetError, Options<CreateTargetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createTarget({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteTargetMutation = (options?: Partial<Options<DeleteTargetData>>): UseMutationOptions<DeleteTargetResponse, DeleteTargetError, Options<DeleteTargetData>> => {
    const mutationOptions: UseMutationOptions<DeleteTargetResponse, DeleteTargetError, Options<DeleteTargetData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteTarget({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthzQueryKey = (options?: Options<HealthzData>) => createQueryKey('healthz', options);

export const healthzOptions = (options?: Options<HealthzData>) => queryOptions<HealthzResponse, DefaultError, HealthzResponse, ReturnType<typeof healthzQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthz({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthzQueryKey(options)
});

export const ingressMutation = (options?: Partial<Options<IngressData>>): UseMutationOptions<unknown, IngressError, Options<IngressData>> => {
    const mutationOptions: UseMutationOptions<unknown, IngressError, Options<IngressData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ingress({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
