// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { CreateEndpointData, CreateEndpointErrors, CreateEndpointResponses, CreateTargetData, CreateTargetErrors, CreateTargetResponses, DeleteTargetData, DeleteTargetErrors, DeleteTargetResponses, HealthzData, HealthzResponses, IngressData, IngressErrors, IngressResponses, ListEndpointsData, ListEndpointsResponses, ListEventsData, ListEventsResponses, ListTargetsData, ListTargetsResponses, UpdateEndpointData, UpdateEndpointErrors, UpdateEndpointResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const listEndpoints = <ThrowOnError extends boolean = false>(options?: Options<ListEndpointsData, ThrowOnError>) => (options?.client ?? client).get<ListEndpointsResponses, unknown, ThrowOnError>({ url: '/api/endpoints', ...options });

export const createEndpoint = <ThrowOnError extends boolean = false>(options: Options<CreateEndpointData, ThrowOnError>) => (options.client ?? client).post<CreateEndpointResponses, CreateEndpointErrors, ThrowOnError>({
    url: '/api/endpoints',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const updateEndpoint = <ThrowOnError extends boolean = false>(options: Options<UpdateEndpointData, ThrowOnError>) => (options.client ?? client).put<UpdateEndpointResponses, UpdateEndpointErrors, ThrowOnError>({
    url: '/api/endpoints/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listEvents = <ThrowOnError extends boolean = false>(options?: Options<ListEventsData, ThrowOnError>) => (options?.client ?? client).get<ListEventsResponses, unknown, ThrowOnError>({ url: '/api/events', ...options });

export const listTargets = <ThrowOnError extends boolean = false>(options?: Options<ListTargetsData, ThrowOnError>) => (options?.client ?? client).get<ListTargetsResponses, unknown, ThrowOnError>({ url: '/api/targets', ...options });

export const createTarget = <ThrowOnError extends boolean = false>(options: Options<CreateTargetData, ThrowOnError>) => (options.client ?? client).post<CreateTargetResponses, CreateTargetErrors, ThrowOnError>({
    url: '/api/targets',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteTarget = <ThrowOnError extends boolean = false>(options: Options<DeleteTargetData, ThrowOnError>) => (options.client ?? client).delete<DeleteTargetResponses, DeleteTargetErrors, ThrowOnError>({ url: '/api/targets/{id}', ...options });

export const healthz = <ThrowOnError extends boolean = false>(options?: Options<HealthzData, ThrowOnError>) => (options?.client ?? client).get<HealthzResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });

export const ingress = <ThrowOnError extends boolean = false>(options: Options<IngressData, ThrowOnError>) => (options.client ?? client).post<IngressResponses, IngressErrors, ThrowOnError>({
    url: '/ingress/{endpoint_id}/{platform}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
