// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AppErrorResponse = {
    error: string;
};

export type CreateEndpointRequest = {
    name: string;
    target_ids: Array<string>;
};

export type CreateTargetRequest = {
    headers?: unknown;
    kind: string;
    name: string;
    url: string;
};

export type DeliveryOutcome = {
    error?: string | null;
    response_code?: number | null;
    status: string;
    target_id: string;
};

export type Endpoint = {
    created_at: number;
    id: string;
    name: string;
    target_ids: Array<string>;
};

export type EventRecord = {
    created_at: number;
    endpoint_id: string;
    id: string;
    markdown: string;
    platform: string;
    raw: unknown;
    title?: string | null;
};

export type Target = {
    created_at: number;
    headers?: unknown;
    id: string;
    kind: string;
    name: string;
    url: string;
};

export type UemEvent = {
    id: string;
    markdown: string;
    meta: unknown;
    raw: unknown;
    source: string;
    timestamp: number;
    title?: string | null;
};

export type UpdateEndpointRequest = {
    name?: string | null;
    target_ids?: Array<string> | null;
};

export type ListEndpointsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/endpoints';
};

export type ListEndpointsResponses = {
    /**
     * List of endpoints
     */
    200: Array<Endpoint>;
};

export type ListEndpointsResponse = ListEndpointsResponses[keyof ListEndpointsResponses];

export type CreateEndpointData = {
    body: CreateEndpointRequest;
    path?: never;
    query?: never;
    url: '/api/endpoints';
};

export type CreateEndpointErrors = {
    /**
     * Bad request
     */
    400: AppErrorResponse;
};

export type CreateEndpointError = CreateEndpointErrors[keyof CreateEndpointErrors];

export type CreateEndpointResponses = {
    /**
     * Endpoint created successfully
     */
    200: Endpoint;
};

export type CreateEndpointResponse = CreateEndpointResponses[keyof CreateEndpointResponses];

export type UpdateEndpointData = {
    body: UpdateEndpointRequest;
    path: {
        /**
         * Endpoint ID
         */
        id: string;
    };
    query?: never;
    url: '/api/endpoints/{id}';
};

export type UpdateEndpointErrors = {
    /**
     * Bad request
     */
    400: AppErrorResponse;
    /**
     * Endpoint not found
     */
    404: AppErrorResponse;
};

export type UpdateEndpointError = UpdateEndpointErrors[keyof UpdateEndpointErrors];

export type UpdateEndpointResponses = {
    /**
     * Endpoint updated successfully
     */
    200: Endpoint;
};

export type UpdateEndpointResponse = UpdateEndpointResponses[keyof UpdateEndpointResponses];

export type ListEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/events';
};

export type ListEventsResponses = {
    /**
     * List of events
     */
    200: Array<EventRecord>;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type ListTargetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/targets';
};

export type ListTargetsResponses = {
    /**
     * List of targets
     */
    200: Array<Target>;
};

export type ListTargetsResponse = ListTargetsResponses[keyof ListTargetsResponses];

export type CreateTargetData = {
    body: CreateTargetRequest;
    path?: never;
    query?: never;
    url: '/api/targets';
};

export type CreateTargetErrors = {
    /**
     * Bad request
     */
    400: AppErrorResponse;
};

export type CreateTargetError = CreateTargetErrors[keyof CreateTargetErrors];

export type CreateTargetResponses = {
    /**
     * Target created successfully
     */
    200: Target;
};

export type CreateTargetResponse = CreateTargetResponses[keyof CreateTargetResponses];

export type DeleteTargetData = {
    body?: never;
    path: {
        /**
         * Target ID
         */
        id: string;
    };
    query?: never;
    url: '/api/targets/{id}';
};

export type DeleteTargetErrors = {
    /**
     * Target not found
     */
    404: AppErrorResponse;
};

export type DeleteTargetError = DeleteTargetErrors[keyof DeleteTargetErrors];

export type DeleteTargetResponses = {
    /**
     * Target deleted successfully
     */
    204: void;
};

export type DeleteTargetResponse = DeleteTargetResponses[keyof DeleteTargetResponses];

export type HealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzResponses = {
    /**
     * Health check
     */
    200: string;
};

export type HealthzResponse = HealthzResponses[keyof HealthzResponses];

export type IngressData = {
    body: unknown;
    path: {
        /**
         * Endpoint ID
         */
        endpoint_id: string;
        /**
         * Platform name
         */
        platform: string;
    };
    query?: never;
    url: '/ingress/{endpoint_id}/{platform}';
};

export type IngressErrors = {
    /**
     * Bad request
     */
    400: AppErrorResponse;
    /**
     * Endpoint not found
     */
    404: AppErrorResponse;
};

export type IngressError = IngressErrors[keyof IngressErrors];

export type IngressResponses = {
    /**
     * Event processed successfully
     */
    200: unknown;
};
